# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmapleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmapleApp
	pod 'AmaniVideo', :git => 'https://github.com/pratuldawande/AmaniVideo.git'

end
